name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym gdown
        pip install -r requirements.txt
    
    - name: Download large file from Google Drive
      run: |
          gdown --fuzzy https://drive.google.com/file/d/1H9s-ZqMpgPeEJ76AzOY1Dlljj8z5UBcd/view?usp=drive_link -O value_net.pkl

    - name: 3. Ensure env.so is executable
      run: chmod +x env.cpython-38-x86_64-linux-gnu.so

    - name: 4. Run Evaluation
      env:
        MODE: 'eval'
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
